apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ms-auth
  namespace: prod
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-ms-auth
  template:
    metadata:
      labels:
        app: backend-ms-auth
        version: "1.00"
    spec:
      containers:
        - name: backend-ms-auth
          image: zebolhd/qa-backend-ms-auth:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qa-config
            - secretRef:
                name: qa-secret
          ports:
            - containerPort: 5500

---
apiVersion: v1
kind: Service
metadata:
  name: backend-ms-auth
  namespace: prod
spec:
  selector:
    app: backend-ms-auth
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
      nodePort: 32600
  type: NodePort
